services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_smartcampus
    ports:
      - "5672:5672"   
      - "15672:15672"  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - smartcampus_net

  
  mongodb:
    image: mongo:6.0
    container_name: mongodb_smartcampus
    ports:
      - "27017:27017" 
    volumes:
      - mongodb_data:/data/db
    networks:
      - smartcampus_net

volumes:
  rabbitmq_data:
  mongodb_data:

networks:
  smartcampus_net:
    driver: bridge