FROM python:3.10-slim

WORKDIR /app

COPY analytics-service/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY analytics-service/ .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]